/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ufrsciencestech.panier.vue;

import fr.ufrsciencestech.panier.controller.ControllerButton;
import fr.ufrsciencestech.panier.modele.Panier;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
/**
 *
 * @author ao469023
 */


public class IHMcomplexe extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form IHMcomplexe
     */
    private Panier panier;
    private ArrayList<String> types;
    private int indSelected=0;
    
    public IHMcomplexe(Panier p) {
        panier = p;
        initTypes();
        ControllerButton cb = new ControllerButton(panier,types.get(indSelected));
        initComponents();
        initComboBox();
        Moins.addActionListener(cb);
        Plus.addActionListener(cb);
    }
    private void initTypes(){
        types=new ArrayList<String>();
        String[] tabFruit={"Orange","Banane","Cerise"};
        String[] tabOrigine={"France","Espagne","Maroc"};
        for(int i=0 ; i<tabFruit.length ; i++)
            for(int j=0; j<tabOrigine.length ; j++)
                types.add(tabFruit[i]+" de "+tabOrigine[j]);
    }
    private void initComboBox(){
        for(String s : types)
            jComboBox1.addItem(s);
    }
    @Override
    public void update(Observable o, Object arg) {        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NORTH = new javax.swing.JPanel();
        Plus = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Moins = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        Plus.setText("+");
        Plus.setName("plusIHM"); // NOI18N
        Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusActionPerformed(evt);
            }
        });
        NORTH.add(Plus);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        NORTH.add(jComboBox1);

        jPanel1.add(NORTH, java.awt.BorderLayout.NORTH);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Moins.setLabel("-");
        Moins.setName("moinsIHM"); // NOI18N
        Moins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoinsActionPerformed(evt);
            }
        });
        jPanel1.add(Moins, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlusActionPerformed

    private void MoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoinsActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMcomplexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMcomplexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMcomplexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMcomplexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
    /*    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHMcomplexe().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Moins;
    private javax.swing.JPanel NORTH;
    private javax.swing.JButton Plus;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
